//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RezaB.Web.Helpers.ColorPallete {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Colors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Colors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RezaB.Web.Helpers.ColorPallete.Colors", typeof(Colors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maroon.
        /// </summary>
        public static string Color01 {
            get {
                return ResourceManager.GetString("Color01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lightgreen.
        /// </summary>
        public static string Color02 {
            get {
                return ResourceManager.GetString("Color02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teal.
        /// </summary>
        public static string Color03 {
            get {
                return ResourceManager.GetString("Color03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chocolate.
        /// </summary>
        public static string Color04 {
            get {
                return ResourceManager.GetString("Color04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to darkblue.
        /// </summary>
        public static string Color05 {
            get {
                return ResourceManager.GetString("Color05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to darkkhaki.
        /// </summary>
        public static string Color06 {
            get {
                return ResourceManager.GetString("Color06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to darkolivegreen.
        /// </summary>
        public static string Color07 {
            get {
                return ResourceManager.GetString("Color07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to darkorange.
        /// </summary>
        public static string Color08 {
            get {
                return ResourceManager.GetString("Color08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to darkslateblue.
        /// </summary>
        public static string Color09 {
            get {
                return ResourceManager.GetString("Color09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to goldenrod.
        /// </summary>
        public static string Color10 {
            get {
                return ResourceManager.GetString("Color10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grey.
        /// </summary>
        public static string Color11 {
            get {
                return ResourceManager.GetString("Color11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indigo.
        /// </summary>
        public static string Color12 {
            get {
                return ResourceManager.GetString("Color12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lightsteelblue.
        /// </summary>
        public static string Color13 {
            get {
                return ResourceManager.GetString("Color13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paleturquoise.
        /// </summary>
        public static string Color14 {
            get {
                return ResourceManager.GetString("Color14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plum.
        /// </summary>
        public static string Color15 {
            get {
                return ResourceManager.GetString("Color15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rosybrown.
        /// </summary>
        public static string Color16 {
            get {
                return ResourceManager.GetString("Color16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to royalblue.
        /// </summary>
        public static string Color17 {
            get {
                return ResourceManager.GetString("Color17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to salmon.
        /// </summary>
        public static string Color18 {
            get {
                return ResourceManager.GetString("Color18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to violet.
        /// </summary>
        public static string Color19 {
            get {
                return ResourceManager.GetString("Color19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yellow.
        /// </summary>
        public static string Color20 {
            get {
                return ResourceManager.GetString("Color20", resourceCulture);
            }
        }
    }
}
